root: ./packages/docs/

redirect:
  operations-manual/key-management/using-a-ledger-wallet: packages/docs/operations-manual/key-management/ledger.md
  operations-manual/key-management/ledger: packages/docs/operations-manual/key-management/ledger.md
  operations-manual/summary/ledger: packages/docs/operations-manual/key-management/ledger.md
  operations-manual/using-a-ledger-wallet: packages/docs/operations-manual/key-management/ledger.md
